services:
  api:
    depends_on:
      - db
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app/src
    environment:
      - DB_TYPE=postgresql
      - DB_USER=postgresuser
      - DB_PASSWORD=pass
      - DB_SERVICE_HOST=db
      - DB_SERVICE_PORT=5432
      - DB_DATABASE=postgres
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=pass
