apiVersion: v1
kind: Service
metadata:
  name: api-np-svc
  namespace: versus
spec:
  type: NodePort
  selector:
    app: versus-bets
    tier: backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
