apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: versus-ingress
  namespace: versus
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-svc
            port:
              number: 8080
      - path: /web
        pathType: Prefix
        backend:
          service:
            name: webapp-svc
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-svc
            port:
              number: 3000
