apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  labels:
    app: versus-bets
    tier: frontend
  namespace: versus
spec:
  selector:
    matchLabels:
      app: versus-bets
      tier: frontend
  template:
    metadata:
      labels:
        app: versus-bets
        tier: frontend
    spec:
      containers:
      - name: web-gui
        image: madzlk/frontend-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://192.168.49.2:30080"
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  namespace: versus
spec:
  selector:
    app: versus-bets
    tier: frontend
  ports:
  - port: 3000
    targetPort: 3000
