apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: versus
spec:
  type: NodePort
  selector:
    app: versus-bets
    tier: frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30030
