apiVersion: v1
kind: Service
metadata:
  name: api-np-svc

spec:
  type: NodePort
  selector:
    app: pm-proc
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
