apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  labels:
    app: pm-proc
    tier: database

spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      component: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        component: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:15
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          env:
            - name: POSTGRESS_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /data/pgdata
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-svc

spec:
  selector:
    component: postgresql-db
  ports:
    - port: 5432
      targetPort: 5432
