apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: pm-proc
    tier: frontend
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
