apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  labels:
    app: pm-proc
    tier: frontend

spec:
  selector:
    matchLabels:
      app: pm-proc
      tier: frontend
  template:
    metadata:
      labels:
        app: pm-proc
        tier: frontend
    spec:
      containers:
        - name: web-gui
          image: madzlk/chakradocbuild:tag
          ports:
            - containerPort: 8000
          env:
            - name: VITE_API_BASE_URL
              value: http://127.0.0.1:56636
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc

spec:
  selector:
    app: pm-proc
    tier: frontend
  ports:
    - port: 8000
      targetPort: 8000
